name: udsm_food_point
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

# packages

dependencies:
  flutter:
    sdk: flutter

  # utility packages

  smooth_page_indicator: ^1.1.0
  http: ^1.2.0
  url_launcher: ^6.2.5
  intl: ^0.19.0
  logger: ^2.1.0
  circular_profile_avatar: ^2.0.5
  awesome_bottom_bar: ^1.2.4
  flutter_native_splash: ^2.3.11

  # icons

  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8
  font_awesome_flutter: ^10.7.0
  flutter_emoji: ^2.5.1
  flutter_spinkit: ^5.2.0

  # state management

  get: ^4.6.5
  get_storage: ^2.1.1
  shared_preferences: ^2.2.2

  # product specific

  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  qr: ^3.0.1
  qr_flutter: ^4.1.0
  qr_image: ^1.0.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^3.0.1


flutter:


  uses-material-design: true

  # local assets

  assets:
    - assets/logos/
    - assets/images/onboarding_images/
    - assets/images/auth_images/
    - assets/images/banners/
    - assets/images/user/
    - assets/images/mobile_ops/
    - assets/images/products/
    - assets/icons/brands/
    - assets/icons/categories/
    - assets/images/success_screen/

  # fonts
  
  fonts:
    - family: NeutriffPro
      fonts:
        - asset: assets/fonts/neutrifpro/NeutrifPro-Light.ttf
          weight: 300
        - asset: assets/fonts/neutrifpro/NeutrifPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/neutrifpro/NeutrifPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/neutrifpro/NeutrifPro-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/neutrifpro/NeutrifPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/neutrifpro/NeutrifPro-Bold.ttf
          weight: 800
        - asset: assets/fonts/neutrifpro/NeutrifPro-RegularItalic.ttf
          style: italic

    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/nunito/Nunito-Medium.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
          weight: 800
 
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open-sans/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/open-sans/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/open-sans/OpenSans-Italic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/open-sans/OpenSans-Semibold.ttf
          weight: 600
        - asset: assets/fonts/open-sans/OpenSans-Bold.ttf
          weight: 800
        - asset: assets/fonts/open-sans/OpenSans-SemiboldItalic.ttf
          style: italic
 
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/playfair-display/PlayfairDisplay-Bold.ttf
          weight: 800

    - family: SanFranciscoPro
      fonts:
        - asset: assets/fonts/San-Francisco/San Francisco/pro/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/San-Francisco/San Francisco/pro/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/San-Francisco/San Francisco/pro/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/San-Francisco/San Francisco/pro/SF-Pro-Display-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/San-Francisco/San Francisco/pro/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/San-Francisco/San Francisco/pro/SF-Pro-Display-Bold.otf
          weight: 800
        - asset: assets/fonts/San-Francisco/San Francisco/pro/SF-Pro-Display-RegularItalic.otf
          style: italic

    


    